name: UploadFile release

on:
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.HTTP.UploadFile
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
